-- Run this in your Supabase SQL Editor

-- 1. USERS TABLE (Enhanced)
-- If table doesn't exist, create it with all fields
create table if not exists users (
  id bigint generated by default as identity primary key,
  full_name text, -- Added
  username text not null,
  email text not null unique,
  phone text, -- Added
  password text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- If table already exists, these commands will add the missing columns.
-- You can run them safely even if you're not sure.
do $$ 
begin 
  if not exists (select 1 from information_schema.columns where table_name = 'users' and column_name = 'full_name') then
    alter table users add column full_name text;
  end if;

  if not exists (select 1 from information_schema.columns where table_name = 'users' and column_name = 'phone') then
    alter table users add column phone text;
  end if;
end $$;

-- 2. CONTACTS TABLE
create table if not exists contacts (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  secondary_phone text,
  address text not null,
  query text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. EMAIL VERIFICATIONS TABLE (For OTP)
create table if not exists email_verifications (
  id bigint generated by default as identity primary key,
  email text not null,
  otp text not null,
  expires_at timestamp with time zone not null,
  verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
